# DOCS: https://github.com/sasstools/sass-lint/tree/master/docs/rules
rules:
  border-zero: { convention: 0 }
  class-name-format:
    convention: hyphenatedlowercase
    allow-leading-underscore: false
  clean-import-paths:
    leading-underscore: false
    filename-extension: false
  declarations-before-nesting: 1
  empty-line-between-blocks:
    include: true
    allow-single-line-rulesets: true
  extends-before-declarations: 1
  extends-before-mixins: 1
  final-newline: { include: true }
  force-attribute-nesting: 0
  force-element-nesting: 0
  force-pseudo-nesting: 0
  hex-length: { style: short }
  hex-notation: { style: lowercase }
  indentation: { size: 2 }
  leading-zero: { include: true }
  max-file-line-count: { length: 9999 }
  max-line-length: { length: 80 }
  mixins-before-declarations: 1
  nesting-depth: { max-depth: 32 }
  no-attribute-selectors: 0
  no-color-hex: 0
  no-color-keywords: 0
  no-color-literals: 0
  no-combinators: 0
  no-css-comments: 0
  no-disallowed-properties:
    properties: []
  no-duplicate-properties:
    exclude: [ display, width, height, top, bottom, left, right ]
  no-empty-rulesets: 1
  no-extends: 0
  no-important: 1
  no-invalid-hex: 2
  no-mergeable-selectors: 1
  no-misspelled-properties: 2
  no-qualifying-elements:
    allow-element-with-attribute: true
    allow-element-with-class: true
    allow-element-with-id: false
  no-trailing-whitespace: 1
  no-trailing-zero: 1
  no-transition-all: 1
  no-universal-selectors: 0
  no-url-domains: 1
  no-url-protocols: 1
  no-vendor-prefixes: 1
  one-declaration-per-line: 1
  property-sort-order: 0
  property-units:
    global: ['%', 'px']
    per-property: { }
  pseudo-element: 1
  quotes: { style: single }
  shorthand-values:
    allowed-shorthands: [ 1, 2 ]
  single-line-per-selector: 1
  space-after-bang: { include: false }
  space-after-colon: { include: true }
  space-after-comma: { include: true }
  space-around-operator: { include: true }
  space-before-bang: { include: true }
  space-before-brace: { include: true }
  space-before-colon: { include: false }
  space-between-parens: { include: false }
  trailing-semicolon: { include: true }
  url-quotes: 1
  variable-for-property:
    properties: [ color, background-color, border-color ]
  zero-unit: { include: false }
